spring:
  datasource:
    url: jdbc:postgresql://localhost:6003/inventory-management-spring-2024
    username: postgres
    password: password


  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

server:
  port: 6060











